import type { MainRole, WimGlobalParams, WimPlayerStats } from "./wim";

export const defaultGlobal = (): WimGlobalParams => ({
  baseAvg: 28,
  baseSr: 130,
  baseBowlAvg: 28,
  baseEcon: 7.8,
  etaV: 1,
  etaE: 1,
  etaO: 1,
  etaODenominatorMin: 1e-9,
  Bmin: 420,
  rhoThresh: 0.18,
  epsilon: 1e-6,
  lb: 0.48,
  hb: 2.18,
  lw: 0.55,
  hw: 2.35,
  lf: 0.35,
  hf: 2.65,
  cLegend: 198,
  ratingPerMatchBonus: 0.0004,
  rpw: 32,
  fScale: 12,
  Imin: 30,
  expectedCatchesPerMatch: 0.18,
  expectedRunoutsPerMatch: 0.04,
  ballsPerWicketPar: 22,
  batWeightAvg: 0.5,
  batWeightSr: 0.5,
  batGeoWeight: 0.58,
  bowlWeightAvg: 0.5,
  bowlWeightEcon: 0.5,
  experienceMatchThreshold: 30,
  experienceGamma: 0.9,
  bowlingSampleGamma: 0.9,
  fieldSampleGamma: 0.9,
  sigmaBallWeight: 0.52,
  sigmaWktWeight: 0.48,
  wicketSigmaKnee: 28,
  /** N_min^wl: full Σ on Bowl_RE only when BF+BB (incl. estimated BB) reaches this career ball budget. */
  bowlingSigmaWorkloadMinBalls: 5500,
  batEliteThreshold: 1.06,
  batEliteSoftness: 0.14,
  batEliteDelta: 0.17,
  batEliteMaxBonus: 0.42,
  bowlEliteThreshold: 1.04,
  bowlEliteSoftness: 0.15,
  bowlEliteDelta: 0.14,
  bowlEliteMaxBonus: 0.35,
  roleDisciplinePhi: 0.98,
});

export const wimModelDefaults: WimGlobalParams = defaultGlobal();

export const defaultPlayer = (name: string, mainRole: MainRole = "allrounder"): WimPlayerStats => ({
  name,
  matches: 48,
  R: 1320,
  dismissals: 44,
  BF: 980,
  wickets: 52,
  runsConceded: 1664,
  catches: 12,
  runouts: 2,
  mainRole,
});
